template = "https://github.com/giellalt/template-lang-und"
rev_id = 313
template_sha = "818c033010c3b7b906621cdeca79061f50bd93ed"

[replacements]
__GLOTTOLOG_ID__ = "kare1335"
__REPO__ = "lang-krl"
__UND2C__ = "krl"
__UNDEFINED__ = "Viena Karelian"
__UND__ = "krl"
