template = "https://github.com/giellalt/template-lang-und"
rev_id = 301
template_sha = "14c7684fb7ae87003fef7c476a4f619d2addefa7"

[replacements]
__GLOTTOLOG_ID__ = "kare1335"
__REPO__ = "lang-krl"
__UND2C__ = "krl"
__UNDEFINED__ = "Viena Karelian"
__UND__ = "krl"
