theme: jekyll-theme-minimal
title: Viena Karelian NLP Grammar
description: Finite state and Constraint Grammar based analysers, proofing tools and language resources for the Viena Karelian language
plugins:
  - jemoji

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
